export const SOD_VIOLATION_DATA = [
  {
    "Control ID": "MC-019",
    "Control name": "Manager Attestation with Evidence Attachment",
    "Policy ID": "P1",
    "Violating user display name": "Ava Bennett",
    "User ID": "ava.bennett001",
    "Master Entitlement": "ZNEW_FICA_CRITICAL_FPAY2",
    "Conflicting Entitlement": "ZNEW_REVENUE_MANUAL_INVOICING",
    "Control owner": "Renee Giles",
    "Mitigation justification":
      "Manager attestation with evidence was accepted in lieu of immediate remediation.",
    "Violation Detection Date": "2026-03-11",
    "Mitigation Start date": "2026-03-12",
    "Mitigation Expiry date": "2026-08-26",
    "Last review date": "2026-03-12",
  },
  {
    "Control ID": "MC-016",
    "Control name": "SIEM Correlation for Toxic Activity",
    "Policy ID": "P1",
    "Violating user display name": "Liam Powell",
    "User ID": "liam.powell002",
    "Master Entitlement": "ZISU_FICA_FEWA_PMT_ERR_SPELIST",
    "Conflicting Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Control owner": "Michael Watkins",
    "Mitigation justification":
      "Cross-system activity requires centralized monitoring; SIEM correlation is used as the mitigating control.",
    "Violation Detection Date": "2026-02-18",
    "Mitigation Start date": "2026-02-18",
    "Mitigation Expiry date": "2026-04-11",
    "Last review date": "2026-02-19",
  },
  {
    "Control ID": "MC-001",
    "Control name": "Independent Payment Approval Review",
    "Policy ID": "P1",
    "Violating user display name": "Mia Parker",
    "User ID": "mia.parker003",
    "Master Entitlement": "ZNEW_FICA_CRITICAL_FPAY2",
    "Conflicting Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Control owner": "Michael Sherman",
    "Mitigation justification":
      "Business continuity required temporary payment release access; independent finance review mitigates the conflict.",
    "Violation Detection Date": "2026-01-06",
    "Mitigation Start date": "2026-01-12",
    "Mitigation Expiry date": "2026-02-26",
    "Last review date": "2026-02-10",
  },
  {
    "Control ID": "MC-019",
    "Control name": "Manager Attestation with Evidence Attachment",
    "Policy ID": "P1",
    "Violating user display name": "Noah Jenkins",
    "User ID": "noah.jenkins004",
    "Master Entitlement": "ZNEW_FICA_CRITICAL_FPAY2",
    "Conflicting Entitlement": "ZMM_ENG_PO",
    "Control owner": "Renee Giles",
    "Mitigation justification":
      "Manager attestation with evidence was accepted in lieu of immediate remediation.",
    "Violation Detection Date": "2026-01-02",
    "Mitigation Start date": "2026-01-02",
    "Mitigation Expiry date": "2026-06-28",
    "Last review date": "2026-02-09",
  },
  {
    "Control ID": "MC-001",
    "Control name": "Independent Payment Approval Review",
    "Policy ID": "P1",
    "Violating user display name": "Ella Price",
    "User ID": "ella.price005",
    "Master Entitlement": "ZNEW_FICA_CRITICAL_FPAY2",
    "Conflicting Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Control owner": "Michael Sherman",
    "Mitigation justification":
      "Business continuity required temporary payment release access; independent finance review mitigates the conflict.",
    "Violation Detection Date": "2026-01-05",
    "Mitigation Start date": "2026-01-07",
    "Mitigation Expiry date": "2026-04-21",
    "Last review date": "2026-02-20",
  },
  {
    "Control ID": "MC-016",
    "Control name": "SIEM Correlation for Toxic Activity",
    "Policy ID": "P1",
    "Violating user display name": "Ethan Perry",
    "User ID": "ethan.perry006",
    "Master Entitlement": "ZISU_FICA_FEWA_PMT_ERR_SPELIST",
    "Conflicting Entitlement": "ZMM_PR_CRE_EU",
    "Control owner": "Michael Watkins",
    "Mitigation justification":
      "Cross-system activity requires centralized monitoring; SIEM correlation is used as the mitigating control.",
    "Violation Detection Date": "2026-02-06",
    "Mitigation Start date": "2026-02-14",
    "Mitigation Expiry date": "2026-05-01",
    "Last review date": "2026-03-12",
  },
  {
    "Control ID": "MC-016",
    "Control name": "SIEM Correlation for Toxic Activity",
    "Policy ID": "P1",
    "Violating user display name": "Sofia Bryant",
    "User ID": "sofia.bryant007",
    "Master Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Conflicting Entitlement": "ZMM_PR_CRE_EU",
    "Control owner": "Michael Watkins",
    "Mitigation justification":
      "Cross-system activity requires centralized monitoring; SIEM correlation is used as the mitigating control.",
    "Violation Detection Date": "2026-03-09",
    "Mitigation Start date": "2026-03-18",
    "Mitigation Expiry date": "2026-05-02",
    "Last review date": "2026-03-18",
  },
  {
    "Control ID": "MC-016",
    "Control name": "SIEM Correlation for Toxic Activity",
    "Policy ID": "P1",
    "Violating user display name": "Lucas Diaz",
    "User ID": "lucas.diaz008",
    "Master Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Conflicting Entitlement": "ZMM_ENG_PO",
    "Control owner": "Michael Watkins",
    "Mitigation justification":
      "Cross-system activity requires centralized monitoring; SIEM correlation is used as the mitigating control.",
    "Violation Detection Date": "2026-01-22",
    "Mitigation Start date": "2026-01-27",
    "Mitigation Expiry date": "2026-06-25",
    "Last review date": "2026-02-09",
  },
  {
    "Control ID": "MC-002",
    "Control name": "New Vendor Verification",
    "Policy ID": "P1",
    "Violating user display name": "Aria Ford",
    "User ID": "aria.ford009",
    "Master Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Conflicting Entitlement": "ZNEW_REVENUE_MANUAL_INVOICING",
    "Control owner": "Kevin Garcia",
    "Mitigation justification":
      "Supplier onboarding duties could not be separated during quarter-end; independent vendor validation is in place.",
    "Violation Detection Date": "2026-02-22",
    "Mitigation Start date": "2026-02-25",
    "Mitigation Expiry date": "2026-04-16",
    "Last review date": "2026-02-25",
  },
  {
    "Control ID": "MC-003",
    "Control name": "Three-Way Match Enforcement",
    "Policy ID": "P1",
    "Violating user display name": "Mason Hunt",
    "User ID": "mason.hunt010",
    "Master Entitlement": "ZISU_FICA_FEWA_PMT_ERR_SPELIST",
    "Conflicting Entitlement": "ZNEW_REVENUE_MANUAL_INVOICING",
    "Control owner": "Michael Sherman",
    "Mitigation justification":
      "Operational need required overlapping invoice/payment access; automated three-way match prevents unauthorized payment.",
    "Violation Detection Date": "2026-01-19",
    "Mitigation Start date": "2026-01-23",
    "Mitigation Expiry date": "2026-03-12",
    "Last review date": "2026-03-11",
  },
  {
    "Control ID": "MC-003",
    "Control name": "Three-Way Match Enforcement",
    "Policy ID": "P2",
    "Violating user display name": "Layla Cruz",
    "User ID": "layla.cruz011",
    "Master Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Conflicting Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Control owner": "Michael Sherman",
    "Mitigation justification":
      "Operational need required overlapping invoice/payment access; automated three-way match prevents unauthorized payment.",
    "Violation Detection Date": "2026-01-14",
    "Mitigation Start date": "2026-01-20",
    "Mitigation Expiry date": "2026-03-01",
    "Last review date": "2026-02-04",
  },
  {
    "Control ID": "MC-004",
    "Control name": "Invoice Exception Review Board",
    "Policy ID": "P2",
    "Violating user display name": "Logan Dunn",
    "User ID": "logan.dunn012",
    "Master Entitlement": "Z_FI_GL_PARK",
    "Conflicting Entitlement": "ZISU_FICA_FEWA_PMT_ERR_SPELIST",
    "Control owner": "Erica Reyes",
    "Mitigation justification":
      "Invoice exceptions must be processed by a small team; review board oversight mitigates the risk.",
    "Violation Detection Date": "2026-02-02",
    "Mitigation Start date": "2026-02-07",
    "Mitigation Expiry date": "2026-07-14",
    "Last review date": "2026-02-09",
  },
  {
    "Control ID": "MC-004",
    "Control name": "Invoice Exception Review Board",
    "Policy ID": "P2",
    "Violating user display name": "Zoe George",
    "User ID": "zoe.george013",
    "Master Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Conflicting Entitlement": "ZNEW_FICA_CRITICAL_FPAY2",
    "Control owner": "Erica Reyes",
    "Mitigation justification":
      "Invoice exceptions must be processed by a small team; review board oversight mitigates the risk.",
    "Violation Detection Date": "2026-01-16",
    "Mitigation Start date": "2026-01-26",
    "Mitigation Expiry date": "2026-03-13",
    "Last review date": "2026-03-12",
  },
  {
    "Control ID": "MC-020",
    "Control name": "Continuous Control Failure Escalation",
    "Policy ID": "P2",
    "Violating user display name": "Leo Howell",
    "User ID": "leo.howell014",
    "Master Entitlement": "Z_FI_GL_PARK",
    "Conflicting Entitlement": "ZISU_FICA_FEWA_PMT_ERR_SPELIST",
    "Control owner": "Jeffrey Martin",
    "Mitigation justification":
      "Residual risk is accepted only with automated escalation if reviews or evidence lapse.",
    "Violation Detection Date": "2026-01-19",
    "Mitigation Start date": "2026-01-23",
    "Mitigation Expiry date": "2026-05-31",
    "Last review date": "2026-02-04",
  },
  {
    "Control ID": "MC-004",
    "Control name": "Invoice Exception Review Board",
    "Policy ID": "P2",
    "Violating user display name": "Nora Oliver",
    "User ID": "nora.oliver015",
    "Master Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Conflicting Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Control owner": "Erica Reyes",
    "Mitigation justification":
      "Invoice exceptions must be processed by a small team; review board oversight mitigates the risk.",
    "Violation Detection Date": "2026-02-24",
    "Mitigation Start date": "2026-03-05",
    "Mitigation Expiry date": "2026-05-03",
    "Last review date": "2026-03-05",
  },
  {
    "Control ID": "MC-003",
    "Control name": "Three-Way Match Enforcement",
    "Policy ID": "P2",
    "Violating user display name": "Jack Gibson",
    "User ID": "jack.gibson016",
    "Master Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Conflicting Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Control owner": "Michael Sherman",
    "Mitigation justification":
      "Operational need required overlapping invoice/payment access; automated three-way match prevents unauthorized payment.",
    "Violation Detection Date": "2026-02-14",
    "Mitigation Start date": "2026-02-20",
    "Mitigation Expiry date": "2026-06-30",
    "Last review date": "2026-02-20",
  },
  {
    "Control ID": "MC-009",
    "Control name": "Time-Bound Exception with Auto-Expiry",
    "Policy ID": "P2",
    "Violating user display name": "Chloe Fleming",
    "User ID": "chloe.fleming017",
    "Master Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Conflicting Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Control owner": "Renee Giles",
    "Mitigation justification":
      "Exception approved for limited duration due to business need; auto-expiry ensures revalidation.",
    "Violation Detection Date": "2026-01-06",
    "Mitigation Start date": "2026-01-10",
    "Mitigation Expiry date": "2026-03-16",
    "Last review date": "2026-02-19",
  },
  {
    "Control ID": "MC-004",
    "Control name": "Invoice Exception Review Board",
    "Policy ID": "P2",
    "Violating user display name": "Henry Barton",
    "User ID": "henry.barton018",
    "Master Entitlement": "Z_FI_GL_PARK",
    "Conflicting Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Control owner": "Erica Reyes",
    "Mitigation justification":
      "Invoice exceptions must be processed by a small team; review board oversight mitigates the risk.",
    "Violation Detection Date": "2025-12-20",
    "Mitigation Start date": "2025-12-26",
    "Mitigation Expiry date": "2026-03-25",
    "Last review date": "2026-03-09",
  },
  {
    "Control ID": "MC-003",
    "Control name": "Three-Way Match Enforcement",
    "Policy ID": "P2",
    "Violating user display name": "Grace Stephens",
    "User ID": "grace.stephens019",
    "Master Entitlement": "ZISU_BILLING_INVOICE_EXECUTION",
    "Conflicting Entitlement": "ZNEW_FICA_CRITICAL_FPAY2",
    "Control owner": "Michael Sherman",
    "Mitigation justification":
      "Operational need required overlapping invoice/payment access; automated three-way match prevents unauthorized payment.",
    "Violation Detection Date": "2025-12-23",
    "Mitigation Start date": "2025-12-26",
    "Mitigation Expiry date": "2026-01-28",
    "Last review date": "2026-01-27",
  },
  {
    "Control ID": "MC-001",
    "Control name": "Independent Payment Approval Review",
    "Policy ID": "P2",
    "Violating user display name": "Owen Goodwin",
    "User ID": "owen.goodwin020",
    "Master Entitlement": "ZNEW_REVENUE_MANUAL_INVOICING",
    "Conflicting Entitlement": "ZNEW_FICA_ACC_PROC_SPVR",
    "Control owner": "Michael Sherman",
    "Mitigation justification":
      "Business continuity required temporary payment release access; independent finance review mitigates the conflict.",
    "Violation Detection Date": "2026-02-27",
    "Mitigation Start date": "2026-03-05",
    "Mitigation Expiry date": "2026-08-18",
    "Last review date": "2026-03-05",
  },
] as const;
